### ISSUE TITLE
online install of the 0.1.1 version fails with sha fingerprint error

### ISSUE THREAD

**Issue by andre-doherty** [OpenLiberty/liberty-tools-eclipse#153] opened 2022-09-06 15:53 UTC
Hello

Installation of the liberty tools fails with the following : 
![image](https://user-images.githubusercontent.com/12730314/188680365-52a3a718-2e99-4abe-9017-2aae082c888a.png)

A workaround is to install the tools with the archive instead.

Regards,

André

**Comment by scottkurz** [comment] 2022-09-06 16:03
@andre-doherty thanks for opening the issue.  

Can you please share your OS/platform and also your Eclipse IDE version and which "package", e.g. "2022-06 , "Eclipse ..for Enterprise Java...".  Or paste a screenshot from:   **Help -> About Eclipse IDE**.

Can I just confirm too that this was the very first version of the Liberty Tools feature you tried to install?   E.g. you didn't try to install the earlier v0.1.0 build when you encountered this error?

Thank you.

**Comment by andre-doherty** [comment] 2022-09-06 16:09
Sure : 
![image](https://user-images.githubusercontent.com/12730314/188683819-6f0e7051-d0cd-4040-88f4-7bdf3cd2a5a4.png)

OS : windows 10 21h2

![image](https://user-images.githubusercontent.com/12730314/188684079-4068a10a-3947-4d87-b813-68a5957fe55e.png)

And yes, that was my first try.

**Comment by andre-doherty** [comment] 2022-09-06 16:18
Note : you might be able to reproduce by : 
- removing the feature
- stop eclipse
- start it again using the -clean option
- install the feature again

**Comment by scottkurz** [comment] 2022-09-09 21:29
I just created a clean ~/.p2 and ~/.eclipse and I was able to install fine from the remote update site.  

I'm confused though because if I manually download the JAR and do `openssl dgst -sha256 ...` against the contents, I see hash values matching the error message... and NOT matching the values within the artifacts.xml file zipped up within the artifacts.jar.     

Reproducing by uninstalling/reinstalling across a `-clean` didn't recreate for me. 

I'm not sure there's anything to conclude for now.  I'm going to reach out to someone internally who I believe hit a similar issue to see what I can learn.

**Comment by scottkurz** [comment] 2022-09-12 19:20
I think we figured out how to fix the problem, which is to update both the `artifacts.jar` AND the `artifacts.xml.xz` files (we'd only updated the latter).

No idea why/when one is used vs. the other though... but it's pretty clearly a bug in our build/release process that we missed that, so we should be able to fix this fairly easily.

**Comment by scottkurz** [comment] 2022-09-18 12:44
Fixed in #162.   This is now available in the 0.2.0 release:  https://github.com/OpenLiberty/liberty-tools-eclipse/releases/tag/liberty-tools-0.2.0

with new update site:  https://raw.githubusercontent.com/OpenLiberty/liberty-tools-eclipse/update-site-0.2

(Note this will install ("update") over an existing, successful install.) 

Please let us know if you have any issues installing.  Hopefully the earlier failure doesn't corrupt the install.

@andre-doherty thank you again for sharing these details.

**Closed by scottkurz** 2022-09-18 12:44 UTC

**Comment by andre-doherty** [comment] 2022-09-26 07:53
Hello Scott,

Thanks for the fix, everything is ok now : i was able to update successfully to version 0.2

André
