### ISSUE TITLE
SVT: Hover does not work for any of the features or elements in server.xml on Windows only

### ISSUE THREAD

**Issue by rumanaHaque** [OpenLiberty/liberty-tools-eclipse#304] opened 2022-12-14 17:08 UTC
After installing Liberty Tools version 0.7.0 (from https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/liberty-tools-eclipse/0.7.0/repository/) 
I cannot hover over any elements in server.xml to get a description.

This happens for all elements in server.xml - even elements like `<httpEndpoint>` and `<ssl>`, and well as features such as `appClientSupport-2.0`.

When I try to add a new feature - then the descriptions are shown for the features to be added, but no pop-ups for the older feature.

**Comment by rumanaHaque** [comment] 2022-12-14 17:11
I had enabled Language server logs for this test.
Tried hovering specifically at 8:50 and 8:57 am. 
Here's the xml file captured.

[org.eclipse.wildwebdeveloper.xml.log](https://github.com/OpenLiberty/liberty-tools-eclipse/files/10230111/org.eclipse.wildwebdeveloper.xml.log)

**Comment by rumanaHaque** [comment] 2022-12-14 18:40
This seems to be Windows specific. Both @jagraj and I see this problem in Windows, but @danielguinan1 doesn't see this using the same driver in Eclipse in Linux.

**Comment by cherylking** [comment] 2022-12-14 21:26
It's also not on all Windows systems, as Scott sees it working on his Windows laptop. So may be a timing issue as well.

**Comment by scottkurz** [comment] 2022-12-15 19:57
By:
> When I try to add a new feature - then the descriptions are shown for the features to be added, but no pop-ups for the older feature.
this still is saying that "hover" is not working".  This description is shown alongside the completion action.

**Comment by scottkurz** [comment] 2023-06-01 16:45
@rumanaHaque curious if you're seeing anything like this in your latest round of testing.

**Comment by rumanaHaque** [comment] 2023-06-01 19:15
And @jagraj confirmed the same behavior using his GarageSale App as well.

**Comment by scottkurz** [comment] 2023-11-10 21:47
I don't expect this is inherently Windows-specific.  It might be that the Windows machines you're using happen to be on the slower side.  The hover timeout in `org.eclipse.lsp4e.operations.hover.LSPTextHover` is only 1s, so it's not too hard to hit.

I'd like to treat this as a duplicate of https://github.com/OpenLiberty/liberty-tools-eclipse/issues/373.  The LS logs there are a bit more complete, and I already closed another issue #396  as dup of that one.

**Closed by scottkurz** 2023-11-10 21:47 UTC
Labels: bug, high priority, SVT
